const toggle=document.querySelector('.menu-toggle'),nav=document.querySelector('.site-nav');
toggle?.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));toggle.textContent=open?'Close':'Menu'});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){nav?.classList.remove('open');toggle?.setAttribute('aria-expanded','false');if(toggle)toggle.textContent='Menu';closeViewer()}});
document.querySelectorAll('.filter-buttons button').forEach(button=>{button.setAttribute('aria-pressed',String(button.classList.contains('active')));button.addEventListener('click',()=>{document.querySelectorAll('.filter-buttons button').forEach(b=>b.setAttribute('aria-pressed',String(b===button)))})});
document.querySelectorAll('a[target="_blank"]').forEach(a=>a.rel='noopener noreferrer');
document.querySelectorAll('.cert-card:not([href])').forEach(a=>{a.href=a.querySelector('img').getAttribute('src')});
document.querySelectorAll('img').forEach((img,i)=>{img.loading='lazy';if(!img.alt)img.alt='Project screenshot '+(i+1)});
let viewerTrigger;
function closeViewer(){const modal=document.getElementById('imageModal');if(modal?.style.display==='flex'){modal.style.display='none';document.body.style.overflow='';viewerTrigger?.focus()}}
const viewer=document.getElementById('imageModal');
if(viewer){viewer.setAttribute('role','dialog');viewer.setAttribute('aria-modal','true');viewer.setAttribute('aria-label','Project screenshot');viewer.removeAttribute('onclick');const old=viewer.querySelector('.close');const close=document.createElement('button');close.className='close';close.textContent='×';close.setAttribute('aria-label','Close image');old.replaceWith(close);close.onclick=closeViewer;viewer.onclick=e=>{if(e.target===viewer)closeViewer()};viewer.addEventListener('keydown',e=>{if(e.key==='Tab'){e.preventDefault();close.focus()}});document.querySelectorAll('.gallery img').forEach(img=>{img.removeAttribute('onclick');const button=document.createElement('button');button.style.cssText='padding:0;border:0;background:none';button.setAttribute('aria-label','Enlarge '+img.alt);img.replaceWith(button);button.append(img);button.onclick=()=>{viewerTrigger=button;document.getElementById('modalImg').src=img.src;document.getElementById('modalImg').alt=img.alt;viewer.style.display='flex';document.body.style.overflow='hidden';close.focus()}})}
